# Jeopardy Topics

In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', 800)


JEOPARDY_CSV =  './data/jeopardy/Jeopardy.csv'

questions = pd.read_csv(JEOPARDY_CSV)

questions = questions.dropna(subset=['Question'])

In [2]:
questions

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was under house arrest for espousing this man's theory",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,"No. 2: 1912 Olympian; football star at Carlisle Indian School; 6 MLB seasons with the Reds, Giants & Braves",Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,"The city of Yuma in this state has a record average of 4,055 hours of sunshine each year",Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", this company served its billionth burger",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Constitution of Mass., second President of the United States",John Adams
5,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$200,"In the title of an Aesop fable, this insect shared billing with a grasshopper",the ant
6,4680,2004-12-31,Jeopardy!,HISTORY,$400,"Built in 312 B.C. to link Rome & the South of Italy, it's still in use today",the Appian Way
7,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$400,"No. 8: 30 steals for the Birmingham Barons; 2,306 steals for the Bulls",Michael Jordan
8,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$400,"In the winter of 1971-72, a record 1,122 inches of snow fell at Rainier Paradise Ranger Station in this state",Washington
9,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$400,This housewares store was named for the packaging its merchandise came in & was first displayed on,Crate & Barrel
10,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$400,"""And away we go""",Jackie Gleason
11,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$400,Cows regurgitate this from the first stomach to the mouth & chew it again,the cud
12,4680,2004-12-31,Jeopardy!,HISTORY,$600,In 1000 Rajaraja I of the Cholas battled to take this Indian Ocean island now known for its tea,Ceylon (or Sri Lanka)
13,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$600,"No. 1: Lettered in hoops, football & lacrosse at Syracuse & if you think he couldn't act, ask his 11 ""unclean"" buddies",Jim Brown
14,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$600,"On June 28, 1994 the nat'l weather service began issuing this index that rates the intensity of the sun's radiation",the UV index
15,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$600,"This company's Accutron watch, introduced in 1960, had a guarantee of accuracy to within one minute a month",Bulova
16,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$600,"Outlaw: ""Murdered by a traitor and a coward whose name is not worthy to appear here""",Jesse James
17,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$600,"A small demon, or a mischievous child (who might be a little demon!)",imp
18,4680,2004-12-31,Jeopardy!,HISTORY,$800,Karl led the first of these Marxist organizational efforts; the second one began in 1889,the International
19,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$800,"No. 10: FB/LB for Columbia U. in the 1920s; MVP for the Yankees in '27 & '36; ""Gibraltar in Cleats""",(Lou) Gehrig
20,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$800,"Africa's lowest temperature was 11 degrees below zero in 1935 at Ifrane, just south of Fez in this country",Morocco
21,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$800,Edward Teller & this man partnered in 1898 to sell high fashions to women,(Paul) Bonwit
22,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,"$2,000","1939 Oscar winner: ""...you are a credit to your craft, your race and to your family""",Hattie McDaniel (for her role in Gone with the Wind)
23,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$800,"In geologic time one of these, shorter than an eon, is divided into periods & subdivided into epochs",era
24,4680,2004-12-31,Jeopardy!,HISTORY,$1000,"This Asian political party was founded in 1885 with ""Indian National"" as part of its name",the Congress Party
25,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$1000,No. 5: Only center to lead the NBA in assists; track scholarship to Kansas U.; marathoner; volleyballer,(Wilt) Chamberlain
26,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$1000,"The Kirschner brothers, Don & Bill, named this ski company for themselves & the second-highest mountain",K2
27,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$1000,"Revolutionary War hero: ""His spirit is in Vermont now""",Ethan Allen
28,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$1000,"A single layer of paper, or to perform one's craft diligently",ply
29,4680,2004-12-31,Double Jeopardy!,DR. SEUSS AT THE MULTIPLEX,$400,"<a href=""http://www.j-archive.com/media/2004-12-31_DJ_23.mp3"">Beyond ovoid abandonment, beyond ovoid betrayal... you won't believe the ending when he ""Hatches the Egg""</a>",Horton
...,...,...,...,...,...,...,...
216900,4999,2006-05-11,Double Jeopardy!,OFF-BROADWAY,$400,"This Baldwin brother was extremely entertaining in the 2006 revival of ""Entertaining Mr. Sloane""",Alec Baldwin
216901,4999,2006-05-11,Double Jeopardy!,RIDDLE ME THIS,$400,He used the strength of his mind when he proposed a riddle to the Philistines in Judges 14,Samson
216902,4999,2006-05-11,Double Jeopardy!,"""T"" BIRDS",$400,"Common species of this duck include blue-winged, green-winged & cinnamon",the teal
216903,4999,2006-05-11,Double Jeopardy!,AUTHORS IN THEIR YOUTH,$400,"As a child, Joseph Conrad pointed to the center of this continent on a map & said, ""I shall go there""",Africa
216904,4999,2006-05-11,Double Jeopardy!,QUOTATIONS,$400,"In 1981 he quipped, ""You can tell a lot about a fellow's character by his way of eating jellybeans""",Ronald Reagan
216905,4999,2006-05-11,Double Jeopardy!,WORLD CAPITALS,$800,It has a museum devoted to composer Zoltan Kodaly,Budapest
216906,4999,2006-05-11,Double Jeopardy!,OFF-BROADWAY,$800,"""Red Light Winter"" centers on a love triangle that begins in the famous Red Light District of this European city",Amsterdam
216907,4999,2006-05-11,Double Jeopardy!,RIDDLE ME THIS,$800,"Sphinx: What animal walks on 4 legs in the morning, 2 at noon & 3 in the evening? Oedipus: This",man
216908,4999,2006-05-11,Double Jeopardy!,"""T"" BIRDS",$800,"Toco, the largest species of this colorful bird of the American tropics, may have a 7-inch bill",a toucan
216909,4999,2006-05-11,Double Jeopardy!,AUTHORS IN THEIR YOUTH,$800,Poet Gregory Corso went on the beat path after meeting this poet in a Greenwich Village bar in 1950,Allen Ginsberg
216910,4999,2006-05-11,Double Jeopardy!,QUOTATIONS,$800,"In his prime this athlete said, It's hard to be humble ""when you're as great as I am""",Muhammad Ali
216911,4999,2006-05-11,Double Jeopardy!,WORLD CAPITALS,$1200,It's home to the Holmenkollen ski jump,Oslo
216912,4999,2006-05-11,Double Jeopardy!,OFF-BROADWAY,$1200,"We'd like to ""enlighten"" you about the musical ""Sidd""; it's based on this novel",Siddhartha
216913,4999,2006-05-11,Double Jeopardy!,RIDDLE ME THIS,$1200,"He created the musical riddles called the ""Enigma Variations""",(Edward) Elgar
216914,4999,2006-05-11,Double Jeopardy!,"""T"" BIRDS",$1200,"One species of this bird breeds in the Arctic tundra & ""vacations"" at the other end of the globe",a tern
216915,4999,2006-05-11,Double Jeopardy!,AUTHORS IN THEIR YOUTH,$1200,In his teens he worked in an assistant D.A.'s office; later his Perry Mason character made fools of D.A.s,(Erle Stanley) Gardner
216916,4999,2006-05-11,Double Jeopardy!,QUOTATIONS,"$2,200","Oscar Wilde called this 4-letter word ""the curse of the drinking classes""",work
216917,4999,2006-05-11,Double Jeopardy!,WORLD CAPITALS,"$3,400",Guyanese capital named for a Hanoverian monarch,Georgetown
216918,4999,2006-05-11,Double Jeopardy!,OFF-BROADWAY,$1600,"A naughty 18th c. novel originally titled ""Memoirs of a Woman of Pleasure"" inspired the 2006 musical named for her",Fanny Hill
216919,4999,2006-05-11,Double Jeopardy!,RIDDLE ME THIS,$1600,"If this riddling Belgian surrealist painter, born 1898 worked for ""Jeopardy!"", he might write, ""This is not a clue""",Magritte
216920,4999,2006-05-11,Double Jeopardy!,"""T"" BIRDS",$1600,Nightingales & robins belong to this family of melodious songbirds,thrushes
216921,4999,2006-05-11,Double Jeopardy!,AUTHORS IN THEIR YOUTH,$1600,Her hotsy-totsy diaries trace back to one she began as an 11-year-old aboard ship in 1914,Anaïs Nin
216922,4999,2006-05-11,Double Jeopardy!,QUOTATIONS,$1600,"A motto of hers was ""in politics, if you want anything said, ask a man; if you want anything done, ask a woman""",(Margaret) Thatcher
216923,4999,2006-05-11,Double Jeopardy!,WORLD CAPITALS,$2000,It's on the Suriname River,Paramaribo
216924,4999,2006-05-11,Double Jeopardy!,OFF-BROADWAY,$2000,"In 2006 the cast of this long-running hit embarked on <a href=""http://www.j-archive.com/media/2006-05-11_DJ_26.wmv"">an exuberant & noisy campaign</a> to clean up New York City",Stomp
216925,4999,2006-05-11,Double Jeopardy!,RIDDLE ME THIS,$2000,This Puccini opera turns on the solution to 3 riddles posed by the heroine,Turandot
216926,4999,2006-05-11,Double Jeopardy!,"""T"" BIRDS",$2000,"In North America this term is properly applied to only 4 species that are crested, including the tufted",a titmouse
216927,4999,2006-05-11,Double Jeopardy!,AUTHORS IN THEIR YOUTH,$2000,"In Penny Lane, where this ""Hellraiser"" grew up, the barber shaves another customer--then flays him alive!",Clive Barker
216928,4999,2006-05-11,Double Jeopardy!,QUOTATIONS,$2000,"From Ft. Sill, Okla. he made the plea, Arizona is my land, my home, my father's land, to which I now ask to... return""",Geronimo
216929,4999,2006-05-11,Final Jeopardy!,HISTORIC NAMES,None,A silent movie title includes the last name of this 18th c. statesman & favorite of Catherine the Great,Grigori Alexandrovich Potemkin

In [3]:
questions['Category'].unique()

array(['HISTORY', "ESPN's TOP 10 ALL-TIME ATHLETES",
       'EVERYBODY TALKS ABOUT IT...', ..., 'OFF-BROADWAY',
       'RIDDLE ME THIS', 'AUTHORS IN THEIR YOUTH'], dtype=object)

In [4]:
len(questions['Category'].unique())

27995

In [5]:
from gensim.parsing.preprocessing import preprocess_string
ques_documents = questions.Question.apply(preprocess_string).tolist()

from gensim import corpora
from gensim.models.ldamodel import LdaModel

dictionary = corpora.Dictionary(ques_documents)
corpus = [dictionary.doc2bow(text) for text in ques_documents]



NUM_TOPICS = 10
ldamodel = LdaModel(corpus, num_topics = NUM_TOPICS, id2word=dictionary, passes=50)


ldamodel.print_topics(num_words=7)

[(0,
  '0.015*"game" + 0.011*"look" + 0.009*"hous" + 0.009*"team" + 0.008*"earli" + 0.008*"offic" + 0.008*"man"'),
 (1,
  '0.028*"word" + 0.027*"clue" + 0.023*"mean" + 0.023*"type" + 0.022*"crew" + 0.017*"letter" + 0.015*"come"'),
 (2,
  '0.020*"presid" + 0.015*"year" + 0.013*"dai" + 0.011*"god" + 0.009*"countri" + 0.009*"state" + 0.008*"mountain"'),
 (3,
  '0.021*"titl" + 0.019*"novel" + 0.019*"book" + 0.017*"wrote" + 0.016*"john" + 0.014*"charact" + 0.013*"author"'),
 (4,
  '0.016*"seen" + 0.013*"american" + 0.013*"british" + 0.013*"long" + 0.011*"king" + 0.010*"french" + 0.009*"took"'),
 (5,
  '0.014*"good" + 0.011*"william" + 0.009*"night" + 0.009*"boi" + 0.008*"poem" + 0.008*"prize" + 0.008*"take"'),
 (6,
  '0.047*"citi" + 0.029*"state" + 0.024*"new" + 0.021*"countri" + 0.018*"capit" + 0.017*"island" + 0.016*"river"'),
 (7,
  '0.029*"plai" + 0.026*"film" + 0.020*"star" + 0.015*"music" + 0.012*"won" + 0.009*"seri" + 0.009*"school"'),
 (8,
  '0.019*"hit" + 0.011*"rock" + 0.010*"big" + 0.009*"number" + 0.009*"bodi" + 0.009*"record" + 0.009*"song"'),
 (9,
  '0.019*"great" + 0.014*"sea" + 0.013*"war" + 0.011*"lake" + 0.010*"end" + 0.010*"right" + 0.009*"robert"')]

In [8]:
ldamodel.log_perplexity(corpus)

-10.145273210821516